import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Center from '../components/layout/center'
import Sidebar from '../components/layout/sidebar'

const Home: NextPage = () => {
  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>
        <Sidebar />
        <Center />
      </main>

    </div>
  )
}

export default Home
